GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMTc0ZTIwMTZkNGU0NTUwMDMzMjlhYyIsInVzZXJuYW1lIjoicmlreW1lZ2dpbyIsImlhdCI6MTY2Mjk3MzM3NX0.43WqsQY2qhksl6x_itxE70jpizQ3o7LX0B98p3pzCuI

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "rikymeggio",
    "password": "@cApriOlo3&n"
}